CREATE DATABASE todolist;
USE todolist;
CREATE TABLE category (id INT NOT NULL AUTO_INCREMENT, cname VARCHAR(50) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE task (id INT NOT NULL AUTO_INCREMENT, label VARCHAR(50) NOT NULL, status BOOL NOT NULL, idCategory INT NOT NULL,
PRIMARY KEY (id), FOREIGN KEY (idCategory) REFERENCES category(id));